- name: configuring mysql server
  hosts: mysql
  become: true
  tasks:
  - name: Install MySQL server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable MySQL server
    ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes 



